### ISSUE TITLE
awakened gems

### ISSUE THREAD

**Issue by beghini21** [Vyary/exile-profit#2]
make something to check the prices of awakened gems lv 5 and 6 please.

**Comment by Vyary** [comment]
Hello,

Please check this link:
https://docs.google.com/spreadsheets/d/1qcYu22DIwEORUYuTJNnYnxS5ceQx8y6XJhVjBai_0lI/edit#gid=520131547&fvid=1324263742

Here "Buy price" is level 1 no quality, "Corrupted 20/20" is level 5/20 corrupted and "Success 21/20" is the same as level 6/20

Best,
Vyary
