### ISSUE TITLE
League

### ISSUE THREAD

**Issue by batzlima** [Vyary/exile-profit#3]
One question, sorry if its dumb. Can you change the code to take the prices in the Crucible League instead of Standard?

**Comment by Vyary** [comment]
Hello there,

The script has been designed to automatically select the current league. What makes you think its standard league so I can investigate it.

Best,
Vyary

**Comment by batzlima** [comment]
Thank you for the reply! I was assuming you had done it for Standard (which is a dumb assumption afterall). Sorry to bother and have a AMAZING day! This code saved my life, my time and filled my pockets. 👍  :)

**Comment by Vyary** [comment]
No worries at all, there are no dumb questions mistakes can be made and prices can get screwed its good to give feedback. I'm glad that my script helped.
